version: '3'
services:

  server:
    build: .
    container_name: avi
    ports:
    - "8000:8000"
    command: sh -c "cd /avito-test
             && alembic upgrade head
             && python main.py"
    env_file:
      - .env
    depends_on:
      - database
    #restart: always

  database:
    image: postgres
    container_name: messager-db
    env_file:
      - .env